#!/bin/sh
if git diff --cached --name-only | grep -E "^Assets/(Magic Light Probes|Bakery)/|^Assets/Editor/x64/Bakery/" >/dev/null; then
  echo "ERROR: Bakery / Magic Light Probes cannot be committed."
  exit 1
fi
